### ISSUE TITLE
Stats are incorrect

### ISSUE THREAD

**Issue by DoggoOfSpeed** [streetcomplete/sc-statistics-service#23]
I'm pretty sure having 10 000 pts should place me higher than last place ![Screenshot_20220425-175707_StreetComplete.jpg](https://user-images.githubusercontent.com/28051112/165116235-c15551e9-fe85-4bac-8335-5fa02fd3d0a8.jpg)

**Versions affected**
Android 12 w/ StreetComplete 42.0

**Comment by westnordost** [comment]
The culprit is that this SQL statement doesn't work anymore as intended:

```sql

INSERT INTO user_ranks (user_id, rank, solved_quest_count)
  SELECT user_id, @rank := @rank + 1 rank, solved_quest_count
  FROM solved_quest_counts_by_user, (SELECT @rank := 0) init
  ORDER BY solved_quest_count DESC;
```

The table `solved_quest_counts_by_user` is simply a mapping of `user_id` to `solved_quest_count`. Intended is that the table is selected ordered by solved quest counts descending and the first row gets rank 1, second gets rank 2 etc.
What it does now is that it selects the table ordered by `user_id`.

**Comment by westnordost** [comment]
I found out that since MariaDB 10.2, there is a function `DENSE_RANK` which does exactly what I did before in this long stored procedure, so I just use that.

Side effects:
- It speeds up the ranks calculation by a lot
- It is much less code

**Comment by westnordost** [comment]
Also, you should charge your phone
